### PR TITLE
Enable C cache to speed up compilation

### PR DESCRIPTION
**Pull request by cachiusa**
In my case, a 53 minutes build have reduced time to only 19 minutes

### CODE REVIEW

**Comment by cd-Crypton** [comment]
I'll test that, thank you.

**Comment by carlodandan** [comment]
I'll check and test that. Thank you.

**Comment by carlodandan** [comment]
Hmmm. But what if the second build is not the same device from previous build? Will it cause issue or will ccache work fine?

**Comment by carlodandan** [comment]
Alright, its already merge anyway. Thanks.

Though making it optional sounds like a good idea too.

**Comment by cachiusa** [comment]
I added that option in #12

**Pull request merged**
